name: On Staging Complete

on:
  repository_dispatch:
    types: [neon_staging_ready]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  seeding:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 🌱 Seeding
        run: |
          echo Run seeding command against the fresh staging system
          echo "PROJECT_ID: ${{ github.event.client_payload.project_id }}"
